name: nacey_flutter_tools
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/roboto_regular.ttf
    - family: Segoe
      fonts:
        - asset: fonts/segoe/segoe.ttf
    - family: SanFrancisco-Pro
      fonts:
        - asset: fonts/sf_pro/sf_pro.ttf
        - asset: fonts/sf_pro/sf_pro_italic.ttf
          style: italic
    - family: SanFrancisco-Compact
      fonts:
        - asset: fonts/sf_compact/sf_compact.ttf
        - asset: fonts/sf_compact/sf_compact_italic.ttf
          style: italic
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
